all: tst_rast tst_mo tst_ren tst_ev tst_eff menu tst_mus game_exe

tst_rast: tst_rast.o raster.o rast_asm.o
	cc68x -g tst_rast.o raster.o rast_asm.o -o tst_rast

tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

tst_mo: tst_mo.o model.o effects.o psg.o
	cc68x -g tst_mo.o model.o effects.o psg.o -o tst_mo

tst_mo.o: tst_mo.c model.h
	cc68x -g -c tst_mo.c

model.o: model.c model.h
	cc68x -g -c model.c

tst_ren: tst_ren.o renderer.o
	cc68x -g tst_ren.o renderer.o raster.o rast_asm.o -o tst_ren

renderer.o: renderer.c renderer.h raster.h 
	cc68x -g -c renderer.c

tst_ren.o: tst_ren.c renderer.h raster.h
	cc68x -g -c tst_ren.c

tst_ev: tst_ev.o events.o model.o effects.o psg.o input.o
	cc68x -g tst_ev.o events.o model.o  effects.o  psg.o input.o -o tst_ev

events.o: events.c events.h model.h effects.h psg.h input.h
	cc68x -g -c events.c

tst_ev.o: tst_ev.c events.h model.h effects.h psg.h input.h
	cc68x -g -c tst_ev.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c

random.o: random.c strike.h model.h
	cc68x -g -c random.c

music.o: music.c music.h psg.h
	cc68x -g -c music.c

tst_mus.o: tst_mus.c tst_mus.h music.h
	cc68x -g -c tst_mus.c

tst_mus: music.o tst_mus.o input.o psg.o
	cc68x -g music.o tst_mus.o input.o psg.o -o tst_mus

game_exe: strike.o input.o model.o events.o renderer.o raster.o rast_asm.o effects.o psg.o random.o music.o
	cc68x -g strike.o input.o model.o events.o renderer.o raster.o rast_asm.o effects.o psg.o random.o music.o -o game_exe

input.o: input.c input.h
	cc68x -g -c input.c

strike.o: strike.c
	cc68x -g -c strike.c

tst_eff: effects.o tst_eff.o psg.o
	cc68x -g effects.o tst_eff.o psg.o -o tst_eff

effects.o: effects.c effects.h
	cc68x -g -c effects.c

menu: menu.o raster.o rast_asm.o
	cc68x -g menu.o raster.o rast_asm.o -o menu

menu.o: menu.c raster.h
	cc68x -g -c menu.c

tst_eff.o: tst_eff.c psg.h effects.h
	cc68x -g -c tst_eff.c