#ifndef TYPES_H
#define TYPES_H

#define TRUE 1
#define FALSE 0

#define SCREEN_HEIGHT 400
#define SCREEN_WIDTH 640

#define PLAYER_ONE 0
#define PLAYER_TWO 1

#define UP_KEY 0x00480000
#define DOWN_KEY 0x00500000
#define RIGHT_KEY 0x004d0000
#define LEFT_KEY 0x004b0000
#define ESC_KEY 27


#define QUIT 1

typedef unsigned char UINT8;
typedef unsigned int  UINT16;
typedef unsigned long UINT32;

#endif
